/**
 * @flow
 */

export const CHECK_APP_SESSION_STATE = 'CHECK_APP_SESSION_STATE';

export const ROUTE_CHANGE = 'ROUTE_CHANGE';
export const ROUTE_REPLACE = 'ROUTE_REPLACE';
export const ROUTE_BACK = 'ROUTE_BACK';

export const FILE_LIST_RESET = 'FILE_LIST_RESET';
export const FILE_LIST_RECEIVED = 'FILE_LIST_RECEIVED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RECEIVED = 'LOGIN_RECEIVED';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_RECEIVED = 'LOGOUT_RECEIVED';

export const SETTINGS_RECEIVED = 'SETTINGS_RECEIVED';

export const VIEWER_IMAGE_GET_URL_RECEIVED = 'VIEWER_IMAGE_GET_URL_RECEIVED';
export const VIEWER_IMAGE_RESET = 'VIEWER_IMAGE_RESET';
export const VIEWER_MEDIA_GET_URL_RECEIVED = 'VIEWER_MEDIA_GET_URL_RECEIVED';
export const VIEWER_MEDIA_RESET = 'VIEWER_MEDIA_RESET';
export const VIEWER_WEB_GET_URL_RECEIVED = 'VIEWER_WEB_GET_URL_RECEIVED';
export const VIEWER_WEB_GET_CONTENT_RECEIVED = 'VIEWER_WEB_GET_CONTENT_RECEIVED';
export const VIEWER_WEB_RESET = 'VIEWER_WEB_RESET';

export const NOTIFICATION_GET_LIST_RECEIVED = 'NOTIFICATION_GET_LIST_RECEIVED';
